feature: custom service deployment
Servers can use the service however clients are throwing an Exception:

com.hazelcast.client.spi.impl.ClientServiceNotFoundException: No factory
registered for service: eyfout/member/service

Additional configuration is needed for clients to use the custom
distributed object. Since the service isn't stateful, I did not
implement Partition, Migration awareness.